name: Build 1C CFE via Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p ./output

      - name: Build CFE using Docker
        run: |
          docker run --rm \
            -v "$(pwd)/src:/src" \
            -v "$(pwd)/output:/output" \
            ghcr.io/evgenyshevchenko/onescript:latest \
            vrunner compile \
              --src /src \
              --out /output/extension.cfe \
              --params "BuildParams"

      - name: Upload CFE artifact
        uses: actions/upload-artifact@v4
        with:
          name: 1C-Extension
          path: ./output/extension.cfe