name: Build 1C CFE via Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p ./output

      - name: Build CFE using vanilla 1C image
        run: |
          docker run --rm \
            -v "$(pwd)/src:/src" \
            -v "$(pwd)/output:/output" \
            ghcr.io/1c-company/edt:latest \
            /opt/1C/v8.3/x86_64/1cv8 \
            DESIGNER /F"/src" /DumpCfg"/output/extension.cfe" /CreateCfe

      - name: Verify CFE file
        run: |
          if [ ! -f "./output/extension.cfe" ]; then
            echo "❌ CFE file was not created!"
            ls -la ./output
            exit 1
          fi
          echo "✅ CFE created successfully"
          ls -lh ./output/extension.cfe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 1C-Extension
          path: ./output/extension.cfe
