name: Build 1C CFE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java (для vrunner)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Download vrunner
        run: |
          mkdir -p ./tools
          wget https://github.com/v8platform/vrunner/releases/latest/download/vrunner-cli-uber.jar -O ./tools/vrunner.jar
          echo "VRN_PATH=$(pwd)/tools" >> $GITHUB_ENV

      - name: Build CFE
        run: |
          mkdir -p ./output
          java -jar $VRN_PATH/vrunner.jar compile \
            --src ./src \
            --out ./output/extension.cfe \
            --params "BuildNumber=${GITHUB_RUN_NUMBER}"

      - name: Verify CFE
        run: |
          if [ ! -f "./output/extension.cfe" ]; then
            echo "❌ CFE file not found!"
            ls -la ./output
            exit 1
          fi
          echo "✅ CFE created: $(ls -lh ./output/extension.cfe)"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 1C-CFE
          path: ./output/extension.cfe
          retention-days: 7
