name: V8Unpack CFE Processing

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unpack-cfe:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Для возможности пушить изменения обратно
    
    - name: Prepare directories
      run: |
        # Создаем выходную директорию
        mkdir -Force out
        # Очищаем предыдущие результаты (если нужно)
        Remove-Item -Path "out/*" -Recurse -Force -ErrorAction SilentlyContinue
      shell: pwsh
        
    - name: Run v8unpack processing
      run: |
        $v8unpackPath = "tools/v8unpack.exe"
        $sourceFile = "src/АнализЦенПоставщиковПоAPI_1_0_5_1.cfe"
        $outputDir = "out"
        
        # Проверяем существование файлов
        if (-not (Test-Path $v8unpackPath)) {
          Write-Host "Error: v8unpack.exe not found in tools directory!"
          exit 1
        }
        
        if (-not (Test-Path $sourceFile)) {
          Write-Host "Error: Source CFE file not found in src directory!"
          exit 1
        }
        
        # Выполняем распаковку
        & $v8unpackPath -E $sourceFile $outputDir
        
        # Проверяем результат
        if (-not (Test-Path "$outputDir/*")) {
          Write-Host "Error: No output files generated!"
          exit 1
        }
        
        Write-Host "Successfully unpacked CFE file to out directory"
      shell: pwsh
      
    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add out/
        git commit -m "CI: Unpacked CFE file [$(Get-Date -Format 'yyyy-MM-dd HH:mm')]"
        git push
      shell: pwsh