name: V8Unpack Processing Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  process-cfe:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Для возможности пушить изменения обратно
    
    - name: Create directories
      run: |
        mkdir -Force out
        mkdir -Force tools
      shell: pwsh
        
    - name: Build v8unpack
      run: |
        cd v8unpack
        call build_local.cmd
      shell: cmd
      
    - name: Run v8unpack processing
      run: |
        $v8unpackPath = "tools/v8unpack.exe"
        $sourceFile = "src/test.cfe"
        $outputDir = "out"
        
        # Копируем собранный v8unpack в tools
        Copy-Item -Path "v8unpack/bin/v8unpack.exe" -Destination $v8unpackPath -Force
        
        # Выполняем распаковку
        & $v8unpackPath -E $sourceFile $outputDir
        
        # Проверяем результат
        if (-not (Test-Path "$outputDir/*")) {
          Write-Host "Error: No output files generated!"
          exit 1
        }
      shell: pwsh
      
    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add out/
        git commit -m "CI: Processed CFE file via v8unpack"
        git push
      shell: pwsh